-- MySQL Script generated by MySQL Workbench
-- Wed Jul 24 16:05:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `USN` INT NOT NULL AUTO_INCREMENT,
  `e_mail` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `birth_date` CHAR(10) NOT NULL,
  `hashed_pwd` CHAR(128) NOT NULL,
  `auth_code` CHAR(128) NULL,
  `timestamp` TIMESTAMP NULL,
  `permission` TINYINT(1) NOT NULL,
  `loginStateFlag` TINYINT(1) NOT NULL,
  `regActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`USN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_app` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_app` (
  `USN` INT NOT NULL,
  `SSN` INT NOT NULL,
  PRIMARY KEY (`USN`),
  CONSTRAINT `fk_User_app_User1`
    FOREIGN KEY (`USN`)
    REFERENCES `mydb`.`User` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sensor_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sensor_Info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sensor_Info` (
  `SSN` INT NOT NULL AUTO_INCREMENT,
  `USN` INT NOT NULL,
  `mac_address` CHAR(12) NOT NULL,
  `sensor_name` VARCHAR(45) NULL,
  `support_service` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NULL,
  `regActive` TINYINT(1) NULL,
  PRIMARY KEY (`SSN`),
  INDEX `fk_Sensor_Info_User_app1_idx` (`USN` ASC) ,
  CONSTRAINT `fk_Sensor_Info_User_app1`
    FOREIGN KEY (`USN`)
    REFERENCES `mydb`.`User_app` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AQI_display`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AQI_display` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AQI_display` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USN` INT NOT NULL,
  `SSN` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `AQI_PM2.5` DOUBLE NOT NULL,
  `AQI_PM10` DOUBLE NOT NULL,
  `AQI_O3` DOUBLE NOT NULL,
  `AQI_NO2` DOUBLE NOT NULL,
  `AQI_CO2` DOUBLE NOT NULL,
  `heart_rate` DOUBLE NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lnt` DOUBLE NOT NULL,
  PRIMARY KEY (`id`, `USN`),
  INDEX `fk_AQI_display_User_app1_idx` (`USN` ASC) ,
  CONSTRAINT `fk_AQI_display_User_app1`
    FOREIGN KEY (`USN`)
    REFERENCES `mydb`.`User_app` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Heart-Rate Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Heart-Rate Sensor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Heart-Rate Sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USN` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `heart_rate` DOUBLE NOT NULL,
  `RR_interval` INT NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  PRIMARY KEY (`id`, `USN`),
  CONSTRAINT `fk_Heart-Rate Sensor_User_app1`
    FOREIGN KEY (`USN`)
    REFERENCES `mydb`.`User_app` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airquality_Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airquality_Sensor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airquality_Sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SSN` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `CO` DOUBLE NOT NULL,
  `SO2` DOUBLE NOT NULL,
  `NO2` DOUBLE NOT NULL,
  `O3` DOUBLE NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `PM2.5` DOUBLE NOT NULL,
  `PM10` DOUBLE NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  PRIMARY KEY (`id`, `SSN`),
  CONSTRAINT `fk_Airquality_Sensor_Sensor_Info1`
    FOREIGN KEY (`SSN`)
    REFERENCES `mydb`.`Sensor_Info` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temp_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Temp_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Temp_user` (
  `e_mail` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `birth_date` CHAR(10) NOT NULL,
  `hashed_pwd` CHAR(128) NOT NULL,
  `auth_code` CHAR(128) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`e_mail`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
